name: genai-gan
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.13
  - pip=24.2
  # Core scientific stack
  - numpy=1.24.4
  - matplotlib
  - scipy
  - pillow
  - h5py
  # Jupyter
  - jupyterlab
  - ipykernel
  - ipywidgets
  - pip:
      - tensorflow==2.13.1
      - keras==2.13.1
